export enum RoleEnum {}

export enum LocaleEnum {
  'en-US' = 'en-US',
  'pt-BR' = 'pt-BR',
  'es-ES' = 'es-ES',
  'ca-ES' = 'ca-ES',
  'de-DE' = 'de-DE',
  'it-IT' = 'it-IT',
  'fr-FR' = 'fr-FR',
  'sv-SE' = 'sv-SE',
  'id-ID' = 'id-ID',
  'pl-PL' = 'pl-PL',
  'ja-JP' = 'ja-JP',
  'zh-TW' = 'zh-TW',
  'zh-CN' = 'zh-CN',
  'ko-KR' = 'ko-KR',
  'th-TH' = 'th-TH',
  'nl-NL' = 'nl-NL',
  'hu-HU' = 'hu-HU',
  'vi-VN' = 'vi-VN',
  'cs-CZ' = 'cs-CZ',
  'da-DK' = 'da-DK',
  'fi-FI' = 'fi-FI',
  'uk-UA' = 'uk-UA',
  'el-GR' = 'el-GR',
  'ro-RO' = 'ro-RO',
  'nb-NO' = 'nb-NO',
  'sk-SK' = 'sk-SK',
  'tr-TR' = 'tr-TR',
  'ru-RU' = 'ru-RU',
}
